---
parameters:
- name: 'applicationName'
  type: string
  displayName: 'Application Name'

- name: 'serviceConnectionName'
  type: string
  displayName: 'Service Connection Name'

- name: 'artifactName'
  type: string
  displayName: 'Build Artifact File Name'

- name: 'keyVaultUriName'
  type: string
  displayName: 'Key Vault Name Used'

- name: 'buildVersion'
  type: string
  displayName: 'Build Version'

steps:

- task: DownloadBuildArtifacts@0
  displayName: 'Download Artifact'
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'release'
    downloadPath: '$(System.ArtifactsDirectory)'


- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy'
  inputs:
    azureSubscription: '${{parameters.serviceConnectionName}}'
    WebAppName: '${{parameters.applicationName}}'
    packageForLinux: '$(System.ArtifactsDirectory)/release/${{parameters.artifactName}}'
    AppSettings: '-KeyVaultName ${{parameters.keyVaultUriName}}'

